name: tsid_dart
description: A TSID Port for Dart libraries or applications. it probably possible to run on any platform, however it was tested on macos and web only.
version: 0.0.5
repository: https://github.com/goeo1066/tsid_dart

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  collection: ^1.18.0
  convert: ^3.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

platforms:
  web:
  macos:
